func = "bar"
arr = [ "qux", "quxx",]
bool1 = 1
bool2 = true
string = "Germany"
fred = "undefined"
emptyArray = []
emptyString = ""
code = [ "a+b=10", "c=a+b", "x=2*c/a+b", "return x",]
base64 = "gAWVKgIAAAAAAACMF2Nsb3VkcGlja2xlLmNsb3VkcGlja2xllIwNX2J1aWx0aW5fdHlwZZSTlIwKTGFtYmRhVHlwZZSFlFKUKGgCjAhDb2RlVHlwZZSFlFKUKEsCSwBLAEsCSwJLQ0MIfAB8ARQAUwCUToWUKYwBY5SMAWSUhpSMPS9ob21lL2FydGVtL1B5dGhvbi9QeXRob240U2VtL2xhYjIvcnVubmluZ19hbGxfc2VyaWFsaXplcnMucHmUjAg8bGFtYmRhPpRLB0MAlCkpdJRSlH2UKIwLX19wYWNrYWdlX1+UTowIX19uYW1lX1+UjAhfX21haW5fX5SMCF9fZmlsZV9flIw9L2hvbWUvYXJ0ZW0vUHl0aG9uL1B5dGhvbjRTZW0vbGFiMi9ydW5uaW5nX2FsbF9zZXJpYWxpemVycy5weZR1Tk5OdJRSlIwcY2xvdWRwaWNrbGUuY2xvdWRwaWNrbGVfZmFzdJSMEl9mdW5jdGlvbl9zZXRzdGF0ZZSTlGgafZR9lChoFWgPjAxfX3F1YWxuYW1lX1+UaA+MD19fYW5ub3RhdGlvbnNfX5R9lIwOX19rd2RlZmF1bHRzX1+UTowMX19kZWZhdWx0c19flE6MCl9fbW9kdWxlX1+UaBaMB19fZG9jX1+UTowLX19jbG9zdXJlX1+UTowXX2Nsb3VkcGlja2xlX3N1Ym1vZHVsZXOUXZSMC19fZ2xvYmFsc19flH2UdYaUhlIwLg=="

[emptyObject]
